// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually
// Models are configured by user during onboarding, not predefined

import type { Model } from "./types.js";

// Empty model registry - users configure their own models during onboarding
export const MODELS = {} as const;

// Get model from user configuration instead of predefined list
export function getUserConfiguredModel(): Model<any> | null {
	// This is a placeholder - actual model loading happens in user-config.ts
	return null;
}
