#!/usr/bin/env tsx

import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const packageRoot = join(__dirname, "..");

// Generate minimal models file - models are configured by user during onboarding
// No predefined models - user configures their own model in the onboarding process
async function generateModels() {
	const output = `// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually
// Models are configured by user during onboarding, not predefined

import type { Model } from "./types.js";

// Empty model registry - users configure their own models during onboarding
export const MODELS = {} as const;

// Get model from user configuration instead of predefined list
export function getUserConfiguredModel(): Model<any> | null {
	// This is a placeholder - actual model loading happens in user-config.ts
	return null;
}
`;

	writeFileSync(join(packageRoot, "src/models.generated.ts"), output);
	console.log("Generated minimal src/models.generated.ts (no predefined models)");
	console.log("Models are configured by user during onboarding");
}

generateModels().catch(console.error);
